# ==================== 配置参数 ====================

# PolarDB Repository Configuration
# 注意需要填写 https 类型的 URL
POLAR_REPO="https://gitee.com/ytsyj/polardb_competition_2025.git"
POLAR_BRANCH="zyt"

# 注意：由于机器环境的限制, 不能同时配置 HNSW 索引和 IVF 索引

# 如果其中一个参数为空, 则不构建 HNSW 索引
HNSW_M=32
HNSW_EF_CONSTRUCTION=360
ef_search_values="30 31 32 33 34 35 36 37 38"

# 如果参数为空, 则不构建 IVF 索引
IVF_LISTS=
probes_values="1 2 5 10 15 20 30 40 50 64 100"

